name: Python Package Builder

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9","3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Branch Name
      run: |
        echo "branch_name=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV               

    - name: Sanitize Branch Name and Git Hash
      run: |
        sanitized_branch_name=$(echo "$branch_name" | sed 's/[^a-zA-Z0-9_-]/_/g')  # Preserving hyphens
        sanitized_git_hash=$(git rev-parse --short "$GITHUB_SHA" | sed 's/[^a-zA-Z0-9_-]/_/g')  # Preserving hyphens
        echo "sanitized_branch_name=$sanitized_branch_name" >> $GITHUB_ENV
        echo "sanitized_git_hash=$sanitized_git_hash" >> $GITHUB_ENV

    - name: Check Branch and Hash
      run: |
        echo "Branch: $sanitized_branch_name"
        echo "Hash: $sanitized_git_hash"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Yarn and React-collapsed
      run:  |
        npm install --global yarn
        npm install react-collapsed

    - name: Install dependencies
      run: python -m pip install --upgrade pip
           pip install allensdk "jupyterlab>=4.0.0,<5"

    - name: Install Node.js dependencies
      run: jlpm install

    - name: Build Extension in Dev Mode
      run: |
        pip install -e .

    - name: Generate description files
      run: |
        python generate_description_files.py
                
    - name: Build Wheel
      run: |
        python -m pip install --upgrade build &&
        python -m build

    - name: Upload Dist Directory Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tvb-ext-xircuits-wheel-${{ env.branch_name }}-${{ env.git_hash }}
        path: dist
