name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Setup Build Env
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install 14.15.3
        nvm use 14.15.3
        npm install --global yarn
        npm install react-collapsed

    - name: Install dependencies
      run: |
        pip install allensdk
        pip install -r requirements.txt

    - name: Build Extension in Dev Mode
      run: |
        pip install -e .

    - name: Generate description files
      run: |
        python generate_description_files.py

    - name: Build Wheel
      run: |
        python -m pip install --upgrade build &&
        python -m build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tvb-ext-xircuits-wheel
        path: dist

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
      run: |
        pip install twine
        twine upload dist/*
