name: Run Python tests

on:
  push:
    branches: '*'
  pull_request:
    branches: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Branch Name
      run: |
          echo "branch_name=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV               

    - name: Sanitize Branch Name and Git Hash
      run: |
        sanitized_branch_name=$(echo "$branch_name" | sed 's/[^a-zA-Z0-9_-]/_/g')  # Preserving hyphens
        sanitized_git_hash=$(git rev-parse --short "$GITHUB_SHA" | sed 's/[^a-zA-Z0-9_-]/_/g')  # Preserving hyphens
        echo "sanitized_branch_name=$sanitized_branch_name" >> $GITHUB_ENV
        echo "sanitized_git_hash=$sanitized_git_hash" >> $GITHUB_ENV

    - name: Check Branch and Hash
      run: |
        echo "Branch: $sanitized_branch_name"
        echo "Hash: $sanitized_git_hash"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install React-collapsed
      run: npm install react-collapsed

    - name: Install Yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install allensdk
          pip install "jupyterlab>=4.0.0,<5" -U pytest pytest-cov pytest-mock

#    - name: Install Node.js dependencies
#      run: jlpm install

    - name: Install Node.js dependencies
      run: jlpm install

    - name: Build Extension in Dev Mode
      run: |
          pip install -e .

    - name: Run tests
      run: |
        pytest tvbextxircuits -r ap

    - name: Compute coverage
      run: |
          pytest -v --cov --cov-report=xml:coverage.xml tvbextxircuits

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}